# Generated by Django 5.2.8 on 2025-11-29 16:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do EPI')),
                ('ca', models.CharField(max_length=20, unique=True, verbose_name='Certificado de Aprovação (CA)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('quantidade_estoque', models.IntegerField(default=0, verbose_name='Qtd. em Estoque')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'EPI',
                'verbose_name_plural': 'EPIs',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade Emprestada')),
                ('data_emprestimo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Empréstimo')),
                ('data_devolucao_prevista', models.DateField(blank=True, null=True, verbose_name='Devolução Prevista')),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução Real')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_gestao.colaborador', verbose_name='Colaborador')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_gestao.epi', verbose_name='EPI')),
            ],
            options={
                'verbose_name': 'Empréstimo de EPI',
                'verbose_name_plural': 'Empréstimos de EPIs',
                'ordering': ['-data_emprestimo'],
            },
        ),
    ]
