# Generated by Django 5.2.8 on 2025-12-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0002_epi_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='observacao_devolucao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação da Devolução'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('emprestado', 'Emprestado'), ('devolvido', 'Devolvido'), ('atrasado', 'Atrasado')], default='emprestado', max_length=20, verbose_name='Status'),
        ),
    ]
